# Ficha de exercícios 1

## 1.1 Matrizes

No final de cada exercício, mostre no ecran o resultado pedido

a) Crie uma matriz chamada "M" com dimensão 10 por 10, preenchida com valores zeros

In [5]:
import numpy as np

temp=(10,10)
M=np.zeros(temp)
print(M)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


b) Preencha com valor 1 todos os valores da borda exterior da matriz (cima, direita, esquerda, baixo)

In [4]:
M[[0,-2],:] = 1
M[:,[0,-2]] = 1
print(M)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


c) Preencha com valor 2 todos os valores da diagonal

In [29]:
np.fill_diagonal(M,2)
print(M)

[[2. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 2. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 2. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 2. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 2. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 2. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 2. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 2. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 2. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 2.]]


d) Crie uma nova chamada "Interior", com dimensão 8x8, e copie a matriz M excluindo os valores das bordas

In [33]:
Interior = (8,8)
Interior = M[1:-1, 1:-1]
print(Interior)

[[2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 2.]]


e) Crie uma nova chamada "I90" com dimensão adequada e copie-lhe a matriz "Interior" rodas para a direita 90 gaus.

In [34]:
I90=(8,8)

I90=np.rot90(Interior)
print(I90)

[[0. 0. 0. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0. 2. 0. 0.]
 [0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 2. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0. 0. 0.]
 [2. 0. 0. 0. 0. 0. 0. 0.]]


f) Crie uma nova chamada "C23" (com dimensão adequada) e copie as colunas 2 e 3 da matriz "Interior"

In [84]:
C23=(2,8)

C23=Interior[:,1:3]
print(C23)

[[0. 0.]
 [2. 0.]
 [0. 2.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


g)  Crie uma nova chamada "O2"  com os valores ordenados os valores da matriz "C23", ordenados por ordem decrescente da coluna 2

In [7]:
O2 = (8,1)
O2=np.sort(C23[:,1])[::-1]
print(O2)

NameError: name 'C23' is not defined

h) Crie uma nova chamada "Aleatorio2" com os valores ordenados de forma aleatoria da matriz "C23"

In [6]:
Aleatorio2= C23
np.random.shuffle(Aleatorio2)
print(Aleatorio2)

NameError: name 'C23' is not defined

## 1.2  Lista 

In [ ]:
Crie um 